#!/bin/sh

# Keyboard
xset r rate 300 20


# IME
export XMODIFIERS='@im=fcitx'
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
## Kitty support
export GLFW_IM_MODULE=ibus

fcitx5 &

# Load keybindings
xmodmap ~/.config/xmodmap/xmodmap

# Wallpaper
xwallpaper --zoom "$HOME/Pictures/wallpapers/vars/wallpaper.png" &

# Deamons
## Clipboard manager
xfce4-clipman &

## Notification
dunst &


## Compositor
picom &

## Bar
~/.config/polybar/launch.sh &

# Start a wm
exec i3
