#!/bin/sh

# Keyboard
xset r rate 300 20

# Load keybindings
xmodmap ~/.config/xmodmap/xmodmap

# Wallpaper
xwallpaper --zoom "$HOME/Pictures/wallpapers/vars/wallpaper.png" &

# Deamons
## Clipboard manager
xfce4-clipman &

## Notification
dunst &

## Bar
~/.config/polybar/launch.sh &

# Start a wm
exec i3
