#!/bin/sh

# Keyboard
xset r rate 300 20

# Clipboard manager
xfce4-clipman &

# Load keybindings
xmodmap ~/.config/xmodmap/xmodmap

# Start a wm
exec dbus-run-session -- sh -c '
  dunst &
  exec spectrwm
'
