# Top Bar
bar_font = xos4 SauceCodeProNerdFont:pixelsize=14:antialias=true
bar_font_pua = Typicons:pixelsize=14:antialias=true
bar_action = scripts/bar_action.sh
bar_format = +L +< +A +|R %Y-%m-%d %H:%M


# Lock
program[lock] = xlock
bind[lock] = Mod4+l


# Clipboard
program[clipman_menu] = xfce4-popup-clipman
bind[clipman_menu] = Mod4+v


# Screenshot
## Fullscreen
### Copy to clipboard
program[ss_fullscreen_copy] = /bin/sh -c 'maim | xclip -selection clipboard -t image/png'
bind[ss_fullscreen_copy] = Mod4+s

### Save to file
program[ss_fullscreen_copy] = /bin/sh -c 'maim | tee "$file"'
bind[ss_fullscreen_copy] = Mod4+Control_L+s

## Select area
### Copy to clipboard
program[ss_select_area_copy] = /bin/sh -c 'maim -s | xclip -selection clipboard -t image/png'
bind[ss_select_area_copy] = Mod4+s

### Save to file
program[ss_select_area_copy] = /bin/sh -c 'maim -s | tee "$file"'
bind[ss_select_area_copy] = Mod4+s
