# Top Bar
## Size
bar_padding_vertical = 4
bar_padding_horizontal = 6

## Font
bar_font = VLPGothic:style=Bold:pixelsize=16:antialias=true
bar_font_pua = Typicons:pixelsize=14:antialias=true


## Content
bar_action = ~/.config/spectrwm/scripts/bar_action.sh
bar_format = +N:+I +S <+D> | +A | +|R  %Y-%m-%d (%a) %H:%M:%S %Z (%s)


# Lock
program[lock] = xlock
bind[lock] = Mod4+l


# Clipboard
program[clipman_menu] = xfce4-popup-clipman
bind[clipman_menu] = Mod4+v


# Launcher
program[rofi] = rofi -show drun
bind[rofi] = Mod4+space


# Screenshot
## Fullscreen
### Copy to clipboard
program[ss_fullscreen_copy] = /bin/sh -c 'maim | xclip -selection clipboard -t image/png'
bind[ss_fullscreen_copy] = Mod4+s

### Save to file
program[ss_fullscreen_copy] = /bin/sh -c 'maim | tee "$file"'
bind[ss_fullscreen_copy] = Mod4+Control_L+s

## Select area
### Copy to clipboard
program[ss_select_area_copy] = /bin/sh -c 'maim -s | xclip -selection clipboard -t image/png'
bind[ss_select_area_copy] = Mod4+s

### Save to file
program[ss_select_area_copy] = /bin/sh -c 'maim -s | tee "$file"'
bind[ss_select_area_copy] = Mod4+s
